[package]
name = "pick_sticks"
version = "0.1.0"
authors = ["raman <tv.raman.tv@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
